In [43]:
import numpy as np

In [44]:
'''
Convolution class using zero padding

param input_num - numbers of input feature maps/images 
param input_size - input feature maps/images size
param filter_size - size of the filter/kernel
param output_num - numbers of output feature maps/images 
param stride - moving step of the kernel function
'''
    

'\nConvolution class using zero padding\n\nparam input_num - numbers of input feature maps/images \nparam input_size - input feature maps/images size\nparam filter_size - size of the filter/kernel\nparam output_num - numbers of output feature maps/images \nparam stride - moving step of the kernel function\n'

In [45]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2

In [46]:
# Check if the parameters of input size, filter size, stride is legel
output_size = (input_size + stride - filter_size) / stride
if(output_size%1 != 0):
    print("Invalid !");

In [5]:
b = np.arange(input_num*input_size*input_size, dtype=np.float).reshape(input_num,input_size,input_size)
print(b)
print(b.strides)
if b.shape!= (input_num,input_size,input_size):
    print("Invalid Input !")

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
(200, 40, 8)


In [6]:
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(input_size*input_size*8), int(input_size*stride*8), int(stride*8), int(input_size*8), 8)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
print(A)
print(A.shape)


# A = A.reshape(int(input_num),int(output_size),int(output_size),int(filter_size*filter_size))     # reshape to one dimention in each kernel
# A = np.insert(A, int(filter_size*filter_size), 1, axis=3)     # Append Bias

[[[[[ 0.  1.  2.]
    [ 5.  6.  7.]
    [10. 11. 12.]]

   [[ 2.  3.  4.]
    [ 7.  8.  9.]
    [12. 13. 14.]]]


  [[[10. 11. 12.]
    [15. 16. 17.]
    [20. 21. 22.]]

   [[12. 13. 14.]
    [17. 18. 19.]
    [22. 23. 24.]]]]



 [[[[25. 26. 27.]
    [30. 31. 32.]
    [35. 36. 37.]]

   [[27. 28. 29.]
    [32. 33. 34.]
    [37. 38. 39.]]]


  [[[35. 36. 37.]
    [40. 41. 42.]
    [45. 46. 47.]]

   [[37. 38. 39.]
    [42. 43. 44.]
    [47. 48. 49.]]]]



 [[[[50. 51. 52.]
    [55. 56. 57.]
    [60. 61. 62.]]

   [[52. 53. 54.]
    [57. 58. 59.]
    [62. 63. 64.]]]


  [[[60. 61. 62.]
    [65. 66. 67.]
    [70. 71. 72.]]

   [[62. 63. 64.]
    [67. 68. 69.]
    [72. 73. 74.]]]]



 [[[[75. 76. 77.]
    [80. 81. 82.]
    [85. 86. 87.]]

   [[77. 78. 79.]
    [82. 83. 84.]
    [87. 88. 89.]]]


  [[[85. 86. 87.]
    [90. 91. 92.]
    [95. 96. 97.]]

   [[87. 88. 89.]
    [92. 93. 94.]
    [97. 98. 99.]]]]]
(4, 2, 2, 3, 3)


In [7]:
# kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
bias = np.arange(output_num, dtype=np.float)
print(kernel)
print(bias)
# print(kernel)
m = np.einsum("ijklm,ailm->ajk", A, kernel)
for i in range(output_num):
    m[i] = m[i] + bias[i]
# m = np.add(m,bias)
# m = np.einsum("ijklm,lm", A_n, kernel)
print(m.shape)
print(m)

[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]

  [[ 18.  19.  20.]
   [ 21.  22.  23.]
   [ 24.  25.  26.]]

  [[ 27.  28.  29.]
   [ 30.  31.  32.]
   [ 33.  34.  35.]]]


 [[[ 36.  37.  38.]
   [ 39.  40.  41.]
   [ 42.  43.  44.]]

  [[ 45.  46.  47.]
   [ 48.  49.  50.]
   [ 51.  52.  53.]]

  [[ 54.  55.  56.]
   [ 57.  58.  59.]
   [ 60.  61.  62.]]

  [[ 63.  64.  65.]
   [ 66.  67.  68.]
   [ 69.  70.  71.]]]


 [[[ 72.  73.  74.]
   [ 75.  76.  77.]
   [ 78.  79.  80.]]

  [[ 81.  82.  83.]
   [ 84.  85.  86.]
   [ 87.  88.  89.]]

  [[ 90.  91.  92.]
   [ 93.  94.  95.]
   [ 96.  97.  98.]]

  [[ 99. 100. 101.]
   [102. 103. 104.]
   [105. 106. 107.]]]]
[0. 1. 2.]
(3, 2, 2)
[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [8]:
error = np.ones(m.shape)
error2 = m
print(error * error2)

[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [9]:
# 
delta_b = np.zeros((input_num, input_size, input_size), dtype=np.float)
delta_w = np.zeros((output_num,input_num,filter_size,filter_size), dtype=np.float)
for img_h in range(len(error[0])):
    for img_w in range(len(error[0][0])):
        left_corner_h = img_h * stride
        left_corner_w = img_w * stride
        for feature in range(len(error)):
            delta_b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] += kernel[feature] * error[feature][img_h][img_w]
            delta_w[feature][:] += b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] * error[feature][img_h][img_w]

print(b)
print(delta_b)
print(delta_w)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
[[[108. 111. 222. 111. 114.]
  [117. 120. 240. 120. 123.]
  [234. 240. 480. 240. 246.]
  [117. 120. 240. 120. 123.]
  [126. 129. 258. 129. 132.]]

 [[135. 138. 276. 138. 141.]
  [144. 147. 294. 147. 150.]
  [288. 294. 588. 294. 300.]
  [144. 147. 294. 147. 150.]
  [153. 156. 312. 156. 159.]]

 [[162. 165. 330. 165. 168.]
  [171. 174. 348. 174. 177.]
  [342. 348. 696. 348. 354.]
  [171. 174. 348. 174. 177.]
  [180. 183. 366. 183. 186.]]

 [[189. 192. 384. 192. 195.]
  [198. 201. 402. 201. 204.]
  [396. 402. 

In [10]:
# a = np.array([1, 2, 3])
# b = np.array([2, 3, 4])
# c = np.array([3, 4, 5])
a = np.empty((3, 4, 4))
print(a)

[[[            nan 4.98429310e-306 1.89131108e-307             nan]
  [            nan 2.49225520e-306 1.52986560e-308             nan]
  [            nan 1.33514447e-307 8.90072459e-306 3.20410364e-306]
  [2.55883324e-307 7.12023296e-307 3.56031102e-306             nan]]

 [[            nan 2.78149680e-307 5.16237506e-306 1.39064995e-309]
  [            nan             nan             nan 2.00256478e-307]
  [5.56330003e-308 1.00132398e-307             nan 4.62819709e-306]
  [8.90029001e-306 2.58125408e-306             nan 4.67265510e-307]]

 [[2.13607090e-306             nan 8.45633317e-307             nan]
  [            nan 6.11912287e-308 4.09443468e-306             nan]
  [            nan             nan 4.45040304e-306             nan]
  [1.16816378e-307             nan             nan             nan]]]


In [25]:

kernel = np.random.randn(output_num,input_num,filter_size,filter_size) / np.sqrt(filter_size*filter_size)
kernel[kernel<=0] = 0
print(kernel)

[[[[0.         0.7672607  0.66004037]
   [0.         0.45026104 0.        ]
   [0.         0.28299738 0.36161759]]

  [[0.         0.29000187 0.        ]
   [0.         0.06492585 0.        ]
   [0.27480305 0.         0.        ]]

  [[0.         0.         0.12050621]
   [0.         0.         0.12857088]
   [0.78700102 0.4292051  0.30620684]]

  [[0.01394683 0.08261835 0.35053687]
   [0.38259582 0.05320867 0.77547678]
   [0.         0.         0.00237833]]]


 [[[0.         0.14762016 0.        ]
   [0.         0.         0.        ]
   [0.         0.         0.11548876]]

  [[0.21025028 0.         0.        ]
   [0.         0.22872654 0.        ]
   [0.1096012  0.38636186 0.        ]]

  [[0.         0.         0.05855125]
   [0.4541562  0.         0.43283155]
   [0.         0.03829234 0.        ]]

  [[0.66031965 0.         0.42096625]
   [0.         0.36892844 0.        ]
   [0.3320596  0.         0.21305932]]]


 [[[0.         0.20226185 0.38710295]
   [0.         0.1637522  0.  

In [7]:
img = np.arange(5*5, dtype=np.float).reshape(1, 5,5)
img[0] = img[0]+ 20
print(img)

[[[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]]]


In [24]:
a = np.full((3, 3, 3), 1/9)
a[a<=0] = 0
print(a)

[[[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]

 [[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]

 [[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]]


In [23]:

b = np.arange(input_num*input_size*input_size, dtype=np.float).reshape(input_num,input_size,input_size)
b = b.reshape(input_num*input_size*input_size)
# a1 = np.sum(b, axis = 0)
# a2 = np.einsum("ijk->i", b)
print(b)
# print(a1)
# print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [41]:
# ans = np.arange(1*3*3, dtype=np.float).reshape(1,3,3)
img = np.arange(1*1*1*3*3, dtype=np.float).reshape(1,1,1,3,3)
img1 = np.arange(2*2*2, dtype=np.float).reshape(2,2,2)
img2 = np.arange(2*2*2, dtype=np.float).reshape(2,2,2)
ans = np.einsum("ijklm,ajk->ailm", img, img1)
print(img)
print(img1)
print(ans)
# delta_bias = np.einsum("ijk->i", img1)
# print(delta_bias)
# img = np.arange(3*3, dtype=np.float).reshape(3,3)
# img1 = np.arange(3, dtype=np.float)
# print(img.dot(img1))
# delta_bias = np.einsum("ijk->i", img1)
# print(delta_bias)
for img_h in range(len(self.img2[0])):
    for img_w in range(len(self.img2[0][0])):
        left_corner_h = img_h * self.stride
        left_corner_w = img_w * self.stride

        for feature in range(len(self.img2)):
            # error pass to previous layer
            img[:,int(left_corner_h):int(left_corner_h+2),int(left_corner_w):int(left_corner_w+2)] += img1[feature] * img2[feature][img_h][img_w]

print(img)

[[[[[0. 1. 2.]
    [3. 4. 5.]
    [6. 7. 8.]]]]]
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
[[[[  0.   6.  12.]
   [ 18.  24.  30.]
   [ 36.  42.  48.]]]


 [[[  0.  22.  44.]
   [ 66.  88. 110.]
   [132. 154. 176.]]]]


NameError: name 'self' is not defined

In [27]:
# kernel = np.random.randn(output_num,input_num,filter_size,filter_size) / np.sqrt(filter_size*filter_size)
kernel = np.random.uniform(5, 100, (2,2,2,4))
print(kernel)

[[[[39.18914466 39.42576822 70.02539607 69.5404457 ]
   [33.72764507 15.45173927 20.16578829 44.75042476]]

  [[21.89591147 73.62606614 54.69484811 13.4438666 ]
   [99.86072017 32.90579243 22.84189786 19.93263679]]]


 [[[99.76361066 47.36127873 77.88034612 25.51250217]
   [78.35210565 84.28848058 23.0574842  52.94967487]]

  [[77.29344137 46.59900598 25.66995505 47.4957926 ]
   [22.00856014 39.52715949 41.11813409 79.84921486]]]]


In [29]:
bias = np.zeros(3)
print(bias)

[0. 0. 0.]


In [35]:
input_num = 2
filter_num = 3
filter_size = 5
bound = np.sqrt(6 / ((input_num + filter_num) * filter_size * filter_size))
kernel = np.random.uniform(-bound, bound, (int(filter_num),int(input_num),int(filter_size),int(filter_size)))
print(bound)
print(kernel.shape)
print(kernel)

0.21908902300206645
(3, 2, 5, 5)
[[[[-0.21623333  0.07857155  0.16452093  0.21333963 -0.11883198]
   [-0.15342482 -0.18710837 -0.18941223  0.02115484  0.08272867]
   [-0.14846792 -0.08412387 -0.12890717  0.19223051  0.07192148]
   [-0.06281566 -0.05970846 -0.1736917  -0.04289954 -0.11927627]
   [ 0.18266185 -0.01339196 -0.11608286 -0.06846983  0.03264627]]

  [[ 0.12507948  0.01828248  0.16361246 -0.11603288  0.2007065 ]
   [ 0.07231331 -0.15042692 -0.20859168  0.16571511 -0.05948562]
   [-0.04304741 -0.01184633 -0.16377563  0.06266435  0.15243055]
   [ 0.05522563 -0.01667682 -0.11284058  0.11712726  0.0701335 ]
   [-0.18458343  0.08846877  0.00532419  0.16878739 -0.14716674]]]


 [[[ 0.11559813 -0.20119163  0.15987269  0.16824482  0.08529101]
   [ 0.07254249  0.16315548  0.07241979  0.16914291 -0.1297881 ]
   [-0.18371354  0.09921822  0.15531905  0.12261937  0.00585741]
   [-0.11571784  0.18043035 -0.06268429  0.14651954 -0.15069337]
   [-0.10403427 -0.0028478   0.12432116  0.01687106

In [119]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2


kernel = np.ones((output_num,int(input_num), filter_size,filter_size))
kernel[1] += 1
kernel[2] += 2
print(kernel)
output_size = int(output_size)
pass_error = np.arange(int(output_num*output_size*output_size), dtype=np.float).reshape(int(output_num),output_size,output_size)
print(pass_error)
# pass_error = pass_error.reshape(output_num, output_size*output_size, 1)
print(pass_error)
# pass_error_tmp = kernel * pass_error
pass_error_tmp = np.einsum("aijk,alm->ilmjk", kernel, pass_error)
print(pass_error_tmp)

b = np.zeros((input_num,input_size,input_size), dtype=np.float)
inv_stride = b.strides
inv_shape = b.shape
print(inv_stride)
print(b)
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(input_size*input_size*8), int(input_size*stride*8), int(stride*8), int(input_size*8), 8)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
print(A)
print(A.shape)
# A += pass_error_tmp
# A = np.concatenate((A,pass_error_tmp), axis =0)
# A = np.add(A[0][0],pass_error_tmp[0][0])
# for i in range(len(pass_error_tmp)):
#     for j in range(len(pass_error_tmp[0])):
#         for k in range(len(pass_error_tmp[0][0])):
#             A[i][j][k] += pass_error_tmp[i][j][k]
for i in range(len(pass_error_tmp[0])):
    for j in range(len(pass_error_tmp[0][0])):
#         print(A[:,i,j], pass_error_tmp[:,i,j])
        A[:,i,j] += pass_error_tmp[:,i,j]
print('----------------A------------')
print(A)
# A[0][0][0] += pass_error_tmp[0][0][0]
# A[0][0][1] += pass_error_tmp[0][0][1]
# A[0][0][1] += pass_error_tmp[1]
# A[0][1] += pass_error_tmp
A = np.lib.stride_tricks.as_strided(A, shape=inv_shape, strides=inv_stride)       # Cut the image with kernel size

print('----------------A inv------------')
print(A)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]]


 [[[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]]]
[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]]
[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]]
[[[[[32. 32. 32.]
    [32. 32. 32.]
    [32. 32. 32.]]

   [[38. 38. 38.]
    [38. 38. 38.]
    [38. 38. 38.]]]


  [[[44. 44. 44.]
    [44. 44. 44.]
    [44. 44. 44.]]

   [[50. 50. 50.]
    [50. 50. 50.]
    [50. 50. 50.]]]]



 [[[[32. 32. 32.]
    [32. 32. 32.]
    [32. 32. 32.]]

   [[38. 38. 38.]
    [38