In [1]:
import numpy as np

In [2]:
'''
Convolution class using zero padding

param input_num - numbers of input feature maps/images 
param input_size - input feature maps/images size
param filter_size - size of the filter/kernel
param output_num - numbers of output feature maps/images 
param stride - moving step of the kernel function
'''
    

'\nConvolution class using zero padding\n\nparam input_num - numbers of input feature maps/images \nparam input_size - input feature maps/images size\nparam filter_size - size of the filter/kernel\nparam output_num - numbers of output feature maps/images \nparam stride - moving step of the kernel function\n'

In [3]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2

In [4]:
# Check if the parameters of input size, filter size, stride is legel
output_size = (input_size + stride - filter_size) / stride
if(output_size%1 != 0):
    print("Invalid !");

In [5]:
b = np.arange(input_num*input_size*input_size, dtype=np.float).reshape(input_num,input_size,input_size)
print(b)
print(b.strides)
if b.shape!= (input_num,input_size,input_size):
    print("Invalid Input !")

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
(200, 40, 8)


In [6]:
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(input_size*input_size*8), int(input_size*stride*8), int(stride*8), int(input_size*8), 8)
print(b)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
print(A)
print(A.shape)


# A = A.reshape(int(input_num),int(output_size),int(output_size),int(filter_size*filter_size))     # reshape to one dimention in each kernel
# A = np.insert(A, int(filter_size*filter_size), 1, axis=3)     # Append Bias

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
[[[[[ 0.  1.  2.]
    [ 5.  6.  7.]
    [10. 11. 12.]]

   [[ 2.  3.  4.]
    [ 7.  8.  9.]
    [12. 13. 14.]]]


  [[[10. 11. 12.]
    [15. 16. 17.]
    [20. 21. 22.]]

   [[12. 13. 14.]
    [17. 18. 19.]
    [22. 23. 24.]]]]



 [[[[25. 26. 27.]
    [30. 31. 32.]
    [35. 36. 37.]]

   [[27. 28. 29.]
    [32. 33. 34.]
    [37. 38. 39.]]]


  [[[35. 36. 37.]
    [40. 41. 42.]
    [45. 46. 47.]]

   [[37. 38. 39.]
    [42. 43. 44.]
    [47. 48. 49.]]]]



 [[[[50. 51. 52.]
    [55. 56. 57.]
    [60. 61. 62.

In [7]:
# kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
bias = np.arange(output_num, dtype=np.float)
print(kernel)
print(bias)
# print(kernel)
m = np.einsum("ijklm,ailm->ajk", A, kernel)
for i in range(output_num):
    m[i] = m[i] + bias[i]
# m = np.add(m,bias)
# m = np.einsum("ijklm,lm", A_n, kernel)
print(m.shape)
print(m)

[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]

  [[ 18.  19.  20.]
   [ 21.  22.  23.]
   [ 24.  25.  26.]]

  [[ 27.  28.  29.]
   [ 30.  31.  32.]
   [ 33.  34.  35.]]]


 [[[ 36.  37.  38.]
   [ 39.  40.  41.]
   [ 42.  43.  44.]]

  [[ 45.  46.  47.]
   [ 48.  49.  50.]
   [ 51.  52.  53.]]

  [[ 54.  55.  56.]
   [ 57.  58.  59.]
   [ 60.  61.  62.]]

  [[ 63.  64.  65.]
   [ 66.  67.  68.]
   [ 69.  70.  71.]]]


 [[[ 72.  73.  74.]
   [ 75.  76.  77.]
   [ 78.  79.  80.]]

  [[ 81.  82.  83.]
   [ 84.  85.  86.]
   [ 87.  88.  89.]]

  [[ 90.  91.  92.]
   [ 93.  94.  95.]
   [ 96.  97.  98.]]

  [[ 99. 100. 101.]
   [102. 103. 104.]
   [105. 106. 107.]]]]
[0. 1. 2.]
(3, 2, 2)
[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [8]:
error = np.ones(m.shape)
error2 = m
print(error * error2)

[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [9]:
# 
delta_b = np.zeros((input_num, input_size, input_size), dtype=np.float)
delta_w = np.zeros((output_num,input_num,filter_size,filter_size), dtype=np.float)
for img_h in range(len(error[0])):
    for img_w in range(len(error[0][0])):
        left_corner_h = img_h * stride
        left_corner_w = img_w * stride
        for feature in range(len(error)):
            delta_b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] += kernel[feature] * error[feature][img_h][img_w]
            delta_w[feature][:] += b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] * error[feature][img_h][img_w]

print(b)
print(delta_b)
print(delta_w)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
[[[108. 111. 222. 111. 114.]
  [117. 120. 240. 120. 123.]
  [234. 240. 480. 240. 246.]
  [117. 120. 240. 120. 123.]
  [126. 129. 258. 129. 132.]]

 [[135. 138. 276. 138. 141.]
  [144. 147. 294. 147. 150.]
  [288. 294. 588. 294. 300.]
  [144. 147. 294. 147. 150.]
  [153. 156. 312. 156. 159.]]

 [[162. 165. 330. 165. 168.]
  [171. 174. 348. 174. 177.]
  [342. 348. 696. 348. 354.]
  [171. 174. 348. 174. 177.]
  [180. 183. 366. 183. 186.]]

 [[189. 192. 384. 192. 195.]
  [198. 201. 402. 201. 204.]
  [396. 402. 

In [10]:
# a = np.array([1, 2, 3])
# b = np.array([2, 3, 4])
# c = np.array([3, 4, 5])
a = np.empty((3, 4, 4))
print(a)

[[[1.44839286e-311 1.44837648e-311 0.00000000e+000 0.00000000e+000]
  [1.15492188e+171 1.16095484e-028 9.20627577e+227 4.82412339e+228]
  [2.32111980e-152 6.77579020e+180 4.87786016e+199 2.31006540e+161]
  [4.93432793e+257 1.08618315e-153 2.32066087e-152 9.82391603e+252]]

 [[4.78719421e+180 1.11130929e+219 3.77073982e+233 3.77704688e+233]
  [1.28153217e-152 2.44141287e-152 1.27967852e-152 2.06745336e+161]
  [6.84979025e+180 1.75304728e-152 5.49684826e+247 9.14985513e+199]
  [1.46921998e+195 1.14448622e+243 1.65115758e+137 1.94577263e+227]]

 [[4.56049677e+257 1.35712977e+166 1.94255855e+227 2.86923143e+180]
  [2.04746607e+161 3.03181447e+180 2.58415103e+161 2.64685963e+180]
  [7.36326086e+223 1.94716794e+227 3.51756346e+180 1.23762449e+224]
  [9.40607967e-119 6.01347176e-154 2.91237123e+257 4.71294503e+257]]]


In [11]:

kernel = np.random.randn(output_num,input_num,filter_size,filter_size) / np.sqrt(filter_size*filter_size)
kernel[kernel<=0] = 0
print(kernel)

[[[[0.42199073 0.68274755 0.03736281]
   [0.         0.         0.4706106 ]
   [0.         0.         0.09437195]]

  [[0.18000207 0.08916441 0.        ]
   [0.         0.23645135 0.0080305 ]
   [0.21223167 0.         0.        ]]

  [[0.66546812 0.         0.        ]
   [0.02483422 0.         0.        ]
   [0.         0.         0.0233562 ]]

  [[0.16590933 0.         0.        ]
   [0.35354432 0.11700268 0.1437738 ]
   [0.09590733 0.07526475 0.        ]]]


 [[[0.01129646 0.15512083 0.        ]
   [0.14901365 0.26239668 0.        ]
   [0.28483214 0.50929329 0.0489659 ]]

  [[0.         0.         0.42142605]
   [0.         0.38529516 0.        ]
   [0.63646493 0.02802897 0.        ]]

  [[0.06033118 0.         0.        ]
   [0.         0.         0.        ]
   [0.10487248 0.59621394 0.        ]]

  [[0.         0.         0.        ]
   [0.         0.49948624 0.34414541]
   [0.         0.         0.00429874]]]


 [[[0.16100102 0.         0.28270024]
   [0.         0.04046297 0.  

In [12]:
img = np.arange(5*5, dtype=np.float).reshape(1, 5,5)
img[0] = img[0]+ 20
print(img)

[[[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]]]


In [13]:
a = np.full((3, 3, 3), 1/9)
a[a<=0] = 0
print(a)

[[[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]

 [[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]

 [[0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]
  [0.11111111 0.11111111 0.11111111]]]


In [14]:

b = np.arange(input_num*input_size*input_size, dtype=np.float).reshape(input_num,input_size,input_size)
b = b.reshape(input_num*input_size*input_size)
# a1 = np.sum(b, axis = 0)
# a2 = np.einsum("ijk->i", b)
print(b)
# print(a1)
# print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [15]:
# ans = np.arange(1*3*3, dtype=np.float).reshape(1,3,3)
img = np.arange(1*1*1*3*3, dtype=np.float).reshape(1,1,1,3,3)
img1 = np.arange(2*2*2, dtype=np.float).reshape(2,2,2)
img2 = np.arange(2*2*2, dtype=np.float).reshape(2,2,2)
ans = np.einsum("ijklm,ajk->ailm", img, img1)
print(img)
print(img1)
print(ans)
# delta_bias = np.einsum("ijk->i", img1)
# print(delta_bias)
# img = np.arange(3*3, dtype=np.float).reshape(3,3)
# img1 = np.arange(3, dtype=np.float)
# print(img.dot(img1))
# delta_bias = np.einsum("ijk->i", img1)
# print(delta_bias)
for img_h in range(len(self.img2[0])):
    for img_w in range(len(self.img2[0][0])):
        left_corner_h = img_h * self.stride
        left_corner_w = img_w * self.stride

        for feature in range(len(self.img2)):
            # error pass to previous layer
            img[:,int(left_corner_h):int(left_corner_h+2),int(left_corner_w):int(left_corner_w+2)] += img1[feature] * img2[feature][img_h][img_w]

print(img)

[[[[[0. 1. 2.]
    [3. 4. 5.]
    [6. 7. 8.]]]]]
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
[[[[  0.   6.  12.]
   [ 18.  24.  30.]
   [ 36.  42.  48.]]]


 [[[  0.  22.  44.]
   [ 66.  88. 110.]
   [132. 154. 176.]]]]


NameError: name 'self' is not defined

In [16]:
# kernel = np.random.randn(output_num,input_num,filter_size,filter_size) / np.sqrt(filter_size*filter_size)
kernel = np.random.uniform(5, 100, (2,2,2,4))
print(kernel)

[[[[23.52797225 11.6245572   7.99558298 39.2755241 ]
   [51.75370134 12.33487131 92.43948549 46.69193985]]

  [[45.76990267 25.36643816 84.11062224 71.48017634]
   [21.80113537 71.34578177 60.15433142 71.33279231]]]


 [[[72.85774167 17.66357318 30.40079542 72.61933729]
   [53.73892973 67.27663488 16.1178768  75.72717719]]

  [[79.19471615 83.07192346 43.52972889 77.3781767 ]
   [45.43233989 14.99305495 59.31340753 77.55722939]]]]


In [17]:
bias = np.zeros(3)
print(bias)

[0. 0. 0.]


In [18]:
input_num = 2
filter_num = 3
filter_size = 5
bound = np.sqrt(6 / ((input_num + filter_num) * filter_size * filter_size))
kernel = np.random.uniform(-bound, bound, (int(filter_num),int(input_num),int(filter_size),int(filter_size)))
print(bound)
print(kernel.shape)
print(kernel)

0.21908902300206645
(3, 2, 5, 5)
[[[[-0.21877343 -0.11136715  0.16195897 -0.06319808 -0.18101471]
   [ 0.09955649 -0.18904496 -0.02212261 -0.11115798 -0.17670441]
   [-0.16310673 -0.00813997 -0.21426158  0.0735433  -0.14823517]
   [ 0.07597901  0.09087169  0.0703681  -0.21677142 -0.08603904]
   [-0.17889099  0.05948969 -0.00202389 -0.00173693  0.10256566]]

  [[ 0.01662137  0.16580309 -0.09044825  0.02098606 -0.00078715]
   [ 0.16228296 -0.16205573  0.19965619 -0.00686756  0.12893416]
   [ 0.08790327 -0.21625545 -0.10849805  0.13806031  0.14453291]
   [-0.06407602 -0.05064033 -0.17990795  0.03173568  0.07077278]
   [-0.08098478 -0.13992685  0.03683543  0.11635658  0.04876244]]]


 [[[-0.02347862 -0.09324695 -0.04902397 -0.17292876 -0.11559111]
   [ 0.09537928  0.16093962  0.15636939 -0.1647184  -0.00581527]
   [ 0.13425997 -0.12206767  0.018621    0.04525627  0.01206294]
   [-0.11147307  0.01249747  0.00606726  0.19203921  0.18986351]
   [ 0.09938733  0.03987715 -0.1156034  -0.09819953

In [19]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2


kernel = np.ones((output_num,int(input_num), filter_size,filter_size))
kernel[1] += 1
kernel[2] += 2
print(kernel)
output_size = int(output_size)
pass_error = np.arange(int(output_num*output_size*output_size), dtype=np.float).reshape(int(output_num),output_size,output_size)
print(pass_error)
# pass_error = pass_error.reshape(output_num, output_size*output_size, 1)
print(pass_error)
# pass_error_tmp = kernel * pass_error
pass_error_tmp = np.einsum("aijk,alm->ilmjk", kernel, pass_error)
print(pass_error_tmp)

b = np.zeros((input_num,input_size,input_size), dtype=np.float)
inv_stride = b.strides
inv_shape = b.shape
print(inv_stride)
print(b)
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(input_size*input_size*8), int(input_size*stride*8), int(stride*8), int(input_size*8), 8)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
print(A)
print(A.shape)
# A += pass_error_tmp
# A = np.concatenate((A,pass_error_tmp), axis =0)
# A = np.add(A[0][0],pass_error_tmp[0][0])
# for i in range(len(pass_error_tmp)):
#     for j in range(len(pass_error_tmp[0])):
#         for k in range(len(pass_error_tmp[0][0])):
#             A[i][j][k] += pass_error_tmp[i][j][k]
for i in range(len(pass_error_tmp[0])):
    for j in range(len(pass_error_tmp[0][0])):
#         print(A[:,i,j], pass_error_tmp[:,i,j])
        A[:,i,j] += pass_error_tmp[:,i,j]
print('----------------A------------')
print(A)
# A[0][0][0] += pass_error_tmp[0][0][0]
# A[0][0][1] += pass_error_tmp[0][0][1]
# A[0][0][1] += pass_error_tmp[1]
# A[0][1] += pass_error_tmp
A = np.lib.stride_tricks.as_strided(A, shape=inv_shape, strides=inv_stride)       # Cut the image with kernel size

print('----------------A inv------------')
print(A)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]

  [[2. 2. 2.]
   [2. 2. 2.]
   [2. 2. 2.]]]


 [[[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]

  [[3. 3. 3.]
   [3. 3. 3.]
   [3. 3. 3.]]]]
[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]]
[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]]
[[[[[32. 32. 32.]
    [32. 32. 32.]
    [32. 32. 32.]]

   [[38. 38. 38.]
    [38. 38. 38.]
    [38. 38. 38.]]]


  [[[44. 44. 44.]
    [44. 44. 44.]
    [44. 44. 44.]]

   [[50. 50. 50.]
    [50. 50. 50.]
    [50. 50. 50.]]]]



 [[[[32. 32. 32.]
    [32. 32. 32.]
    [32. 32. 32.]]

   [[38. 38. 38.]
    [38

In [20]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2

output_size = (input_size + stride - filter_size) / stride
if(output_size%1 != 0):
    print("Invalid !");
kernel = np.ones((output_num,int(input_num), filter_size,filter_size))
kernel[1] += 1
kernel[2] += 2
# print(kernel)
output_size = int(output_size)

# error passed over
pass_error = np.arange(int(output_num*output_size*output_size), dtype=np.float).reshape(int(output_num),output_size,output_size)

pass_error_tmp = np.einsum("aijk,alm->ilmjk", kernel, pass_error)
# print(pass_error_tmp)

# Use to map error position
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(output_size*output_size*input_size*input_size*8), int((input_size * input_size + input_size)*stride*8), int((input_size * input_size + stride)*8), int(input_size*8), 8)

print('----------------------b-----------------------')
# b = np.arange(int(input_num)*int(output_size)*int(output_size)*int(input_size)*int(input_size), dtype=np.float).reshape(int(input_num),int(output_size),int(output_size),int(input_size),int(input_size))
b = np.zeros((int(input_num),int(output_size),int(output_size),int(input_size),int(input_size)), dtype=np.float)
inv_stride = b.strides
inv_shape = b.shape
print(inv_stride)
# print(b)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
# print(A)
print(A.shape)
A += pass_error_tmp
A = np.lib.stride_tricks.as_strided(A, shape=inv_shape, strides=inv_stride)       # Cut the image with kernel size
b = np.einsum("ijklm->ilm", A)

print('----------------A inv------------')
print(A)
print('----------------B------------')
print(b)

----------------------b-----------------------
(800, 400, 200, 40, 8)
(4, 2, 2, 3, 3)
----------------A inv------------
[[[[[32. 32. 32.  0.  0.]
    [32. 32. 32.  0.  0.]
    [32. 32. 32.  0.  0.]
    [ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]]

   [[ 0.  0. 38. 38. 38.]
    [ 0.  0. 38. 38. 38.]
    [ 0.  0. 38. 38. 38.]
    [ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]]]


  [[[ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]
    [44. 44. 44.  0.  0.]
    [44. 44. 44.  0.  0.]
    [44. 44. 44.  0.  0.]]

   [[ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]
    [ 0.  0. 50. 50. 50.]
    [ 0.  0. 50. 50. 50.]
    [ 0.  0. 50. 50. 50.]]]]



 [[[[32. 32. 32.  0.  0.]
    [32. 32. 32.  0.  0.]
    [32. 32. 32.  0.  0.]
    [ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]]

   [[ 0.  0. 38. 38. 38.]
    [ 0.  0. 38. 38. 38.]
    [ 0.  0. 38. 38. 38.]
    [ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]]]


  [[[ 0.  0.  0.  0.  0.]
    [ 0.  0.  0.  0.  0.]
    [44. 44. 44.  0.  0.]
  

In [21]:
b.fill(0)
print(b)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
