In [1]:
import numpy as np

In [2]:
'''
Convolution class using zero padding

param input_num - numbers of input feature maps/images 
param input_size - input feature maps/images size
param filter_size - size of the filter/kernel
param output_num - numbers of output feature maps/images 
param stride - moving step of the kernel function
'''
    

'\nConvolution class using zero padding\n\nparam input_num - numbers of input feature maps/images \nparam input_size - input feature maps/images size\nparam filter_size - size of the filter/kernel\nparam output_num - numbers of output feature maps/images \nparam stride - moving step of the kernel function\n'

In [3]:
# Test parameters
input_num = 4
input_size = 5
filter_size = 3
output_num = 3
stride = 2

In [4]:
# Check if the parameters of input size, filter size, stride is legel
output_size = (input_size + stride - filter_size) / stride
if(output_size%1 != 0):
    print("Invalid !");

In [5]:
b = np.arange(input_num*input_size*input_size, dtype=np.float).reshape(input_num,input_size,input_size)
print(b)
print(b.strides)
if b.shape!= (input_num,input_size,input_size):
    print("Invalid Input !")

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
(200, 40, 8)


In [6]:
img_shape = (int(input_num),int(output_size),int(output_size),int(filter_size),int(filter_size))
img_strides = (int(input_size*input_size*8), int(input_size*stride*8), int(stride*8), int(input_size*8), 8)
A = np.lib.stride_tricks.as_strided(b, shape=img_shape, strides=img_strides)       # Cut the image with kernel size
print(A)
print(A.shape)


# A = A.reshape(int(input_num),int(output_size),int(output_size),int(filter_size*filter_size))     # reshape to one dimention in each kernel
# A = np.insert(A, int(filter_size*filter_size), 1, axis=3)     # Append Bias

[[[[[ 0.  1.  2.]
    [ 5.  6.  7.]
    [10. 11. 12.]]

   [[ 2.  3.  4.]
    [ 7.  8.  9.]
    [12. 13. 14.]]]


  [[[10. 11. 12.]
    [15. 16. 17.]
    [20. 21. 22.]]

   [[12. 13. 14.]
    [17. 18. 19.]
    [22. 23. 24.]]]]



 [[[[25. 26. 27.]
    [30. 31. 32.]
    [35. 36. 37.]]

   [[27. 28. 29.]
    [32. 33. 34.]
    [37. 38. 39.]]]


  [[[35. 36. 37.]
    [40. 41. 42.]
    [45. 46. 47.]]

   [[37. 38. 39.]
    [42. 43. 44.]
    [47. 48. 49.]]]]



 [[[[50. 51. 52.]
    [55. 56. 57.]
    [60. 61. 62.]]

   [[52. 53. 54.]
    [57. 58. 59.]
    [62. 63. 64.]]]


  [[[60. 61. 62.]
    [65. 66. 67.]
    [70. 71. 72.]]

   [[62. 63. 64.]
    [67. 68. 69.]
    [72. 73. 74.]]]]



 [[[[75. 76. 77.]
    [80. 81. 82.]
    [85. 86. 87.]]

   [[77. 78. 79.]
    [82. 83. 84.]
    [87. 88. 89.]]]


  [[[85. 86. 87.]
    [90. 91. 92.]
    [95. 96. 97.]]

   [[87. 88. 89.]
    [92. 93. 94.]
    [97. 98. 99.]]]]]
(4, 2, 2, 3, 3)


In [7]:
# kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
kernel = np.arange(output_num*input_num*filter_size*filter_size, dtype=np.float).reshape(output_num,input_num,filter_size,filter_size)
bias = np.arange(output_num, dtype=np.float)
print(kernel)
print(bias)
# print(kernel)
m = np.einsum("ijklm,ailm->ajk", A, kernel)
for i in range(output_num):
    m[i] = m[i] + bias[i]
# m = np.add(m,bias)
# m = np.einsum("ijklm,lm", A_n, kernel)
print(m.shape)
print(m)

[[[[  0.   1.   2.]
   [  3.   4.   5.]
   [  6.   7.   8.]]

  [[  9.  10.  11.]
   [ 12.  13.  14.]
   [ 15.  16.  17.]]

  [[ 18.  19.  20.]
   [ 21.  22.  23.]
   [ 24.  25.  26.]]

  [[ 27.  28.  29.]
   [ 30.  31.  32.]
   [ 33.  34.  35.]]]


 [[[ 36.  37.  38.]
   [ 39.  40.  41.]
   [ 42.  43.  44.]]

  [[ 45.  46.  47.]
   [ 48.  49.  50.]
   [ 51.  52.  53.]]

  [[ 54.  55.  56.]
   [ 57.  58.  59.]
   [ 60.  61.  62.]]

  [[ 63.  64.  65.]
   [ 66.  67.  68.]
   [ 69.  70.  71.]]]


 [[[ 72.  73.  74.]
   [ 75.  76.  77.]
   [ 78.  79.  80.]]

  [[ 81.  82.  83.]
   [ 84.  85.  86.]
   [ 87.  88.  89.]]

  [[ 90.  91.  92.]
   [ 93.  94.  95.]
   [ 96.  97.  98.]]

  [[ 99. 100. 101.]
   [102. 103. 104.]
   [105. 106. 107.]]]]
[0. 1. 2.]
(3, 2, 2)
[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [14]:
error = np.ones(m.shape)
error2 = m
print(error * error2)

[[[ 37914.  39174.]
  [ 44214.  45474.]]

 [[ 94291.  98143.]
  [113551. 117403.]]

 [[150668. 157112.]
  [182888. 189332.]]]


In [9]:
# 
delta_b = np.zeros((input_num, input_size, input_size), dtype=np.float)
delta_w = np.zeros((output_num,input_num,filter_size,filter_size), dtype=np.float)
for img_h in range(len(error[0])):
    for img_w in range(len(error[0][0])):
        left_corner_h = img_h * stride
        left_corner_w = img_w * stride
        for feature in range(len(error)):
            delta_b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] += kernel[feature] * error[feature][img_h][img_w]
            delta_w[feature][:] += b[:,left_corner_h:(left_corner_h+filter_size),left_corner_w:(left_corner_w+filter_size)] * error[feature][img_h][img_w]

print(b)
print(delta_b)
print(delta_w)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]
  [40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]]

 [[50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64.]
  [65. 66. 67. 68. 69.]
  [70. 71. 72. 73. 74.]]

 [[75. 76. 77. 78. 79.]
  [80. 81. 82. 83. 84.]
  [85. 86. 87. 88. 89.]
  [90. 91. 92. 93. 94.]
  [95. 96. 97. 98. 99.]]]
[[[108. 111. 222. 111. 114.]
  [117. 120. 240. 120. 123.]
  [234. 240. 480. 240. 246.]
  [117. 120. 240. 120. 123.]
  [126. 129. 258. 129. 132.]]

 [[135. 138. 276. 138. 141.]
  [144. 147. 294. 147. 150.]
  [288. 294. 588. 294. 300.]
  [144. 147. 294. 147. 150.]
  [153. 156. 312. 156. 159.]]

 [[162. 165. 330. 165. 168.]
  [171. 174. 348. 174. 177.]
  [342. 348. 696. 348. 354.]
  [171. 174. 348. 174. 177.]
  [180. 183. 366. 183. 186.]]

 [[189. 192. 384. 192. 195.]
  [198. 201. 402. 201. 204.]
  [396. 402. 

In [10]:
# a = np.array([1, 2, 3])
# b = np.array([2, 3, 4])
# c = np.array([3, 4, 5])
print(int(5/2))

2


In [11]:

kernel = np.random.randn(output_num,input_num,filter_size,filter_size) / np.sqrt(filter_size*filter_size)
print(kernel)

[[[[-0.29194739  0.22644032  0.2685401 ]
   [ 0.26467858 -0.0098676   0.32350612]
   [-0.24338977 -0.32731132  0.20255714]]

  [[ 0.12594621 -0.11099998 -0.08426123]
   [ 0.01988411 -0.30991283  0.01325068]
   [-0.05404398  0.44587106 -0.20928203]]

  [[-0.02456025  0.1194065  -0.43439483]
   [-0.5290554   0.29755186  0.13255597]
   [-0.3325178   0.60380419  0.05456403]]

  [[-0.90515867  0.2416779  -0.32715772]
   [ 0.31804141 -0.11335192 -0.75436731]
   [-0.82446563  0.22621014  0.03363391]]]


 [[[-0.30203088  0.37888896 -0.17135454]
   [ 0.09211025  0.34505802 -0.09757984]
   [ 0.24769464  0.02162588  0.56571379]]

  [[ 0.08018809 -0.34870918 -0.02303904]
   [-0.28288698 -1.11027012  0.44167385]
   [-0.16183811  0.28404843  0.27529213]]

  [[-0.05566486  0.05988651  0.19409303]
   [-0.19102447  0.20490464  0.0202142 ]
   [ 0.02505173  0.12911134  0.59035875]]

  [[ 0.09679801  0.01924823  0.2750486 ]
   [ 0.1125727  -0.20991747 -0.05061581]
   [-0.00524669  0.24013042  0.31770866]]